name: OpenRia Build
env:
  solution: 'OpenRiaServices.OpenSilver.sln'
on:
  # We run the process manually and pass the version of actual OpenSilver
  workflow_dispatch:
    inputs:
      opensilver-version:
        description: 'OpenSilver package version'
        required: true
jobs:
  OpenRia-Build:
    runs-on: windows-latest
    steps:
      - uses: microsoft/setup-msbuild@v1.0.3
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.101'
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Remove OpenSilver packages for all projects
        run: |
          foreach ($project in dotnet sln ${{ env.solution }} list | Select-Object -Skip 2) {
            dotnet remove $project package OpenSilver
            if (-not $?) {throw "Failed to remove package"}
          }
        env:
          DOTNET_NOLOGO: true
      - name: Add OpenSilver package for all projects
        run: |
          foreach ($project in dotnet sln ${{ env.solution }} list | Select-Object -Skip 2) {
            dotnet add $project package OpenSilver -v ${{ github.event.inputs.opensilver-version }}
            if (-not $?) {throw "Failed to add package"}
          }
        env:
          DOTNET_NOLOGO: true
      - name: Build solution
        run: |
          msbuild ${{ env.solution }} -p:Configuration=Release -clp:ErrorsOnly -restore
      - name: Format Package Version
        id: version
        run: echo "::set-output name=suffix::$(date +'%Y-%m-%d-%H%M%S')-${{ env.GITHUB_SHA_SHORT }}"
      - name: Build packages
        working-directory: OpenRiaServices.NuGet
        run: |
          .\Pack-Client-OS.ps1 -Version 1.0.0-private-${{ steps.version.outputs.suffix }} -OpenSilverDependencyVersion ${{ github.event.inputs.opensilver-version }} -RepositoryUrl https://github.com/${{ env.GITHUB_REPOSITORY_OWNER_PART }}/${{ env.GITHUB_REPOSITORY_NAME_PART }}
      - name: Upload packages
        run: |
           dotnet nuget push "OpenRiaServices.NuGet\bin\opensilver\*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/${{ env.GITHUB_REPOSITORY_OWNER_PART }}/index.json
      - name: Upload packages to MyGet
        run: |
           dotnet nuget push "OpenRiaServices.NuGet\bin\opensilver\*.nupkg" -k ${{ secrets.MYGET_TOKEN }} -s https://www.myget.org/F/opensilver/api/v2/package