name: OpenRia Build
on:
  # We run the process manually and pass the version of actual OpenSilver
  workflow_dispatch:
    inputs:
      opensilver-version:
        description: 'OpenSilver package version'
        required: true
jobs:
  OpenRia-Build:
    runs-on: windows-latest
    steps:
      - uses: microsoft/setup-msbuild@v1.0.3
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.101'
          source-url: https://nuget.pkg.github.com/OpenSilver/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
